import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../controllers/project_controller.dart';
import '../models/project.dart';
import '../widgets/themed_app_bar.dart';

class AdminPage extends StatefulWidget {
  const AdminPage({super.key});

  @override
  State<AdminPage> createState() => _AdminPageState();
}

class _AdminPageState extends State<AdminPage> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _imageUrlController = TextEditingController();
  final _technologiesController = TextEditingController();
  final _githubLinkController = TextEditingController();

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    _imageUrlController.dispose();
    _technologiesController.dispose();
    _githubLinkController.dispose();
    super.dispose();
  }

  void _submitForm() {
    if (_formKey.currentState!.validate()) {
      final newProject = Project(
        id: '', // ID will be generated by the controller
        title: _titleController.text,
        description: _descriptionController.text,
        imageUrl: _imageUrlController.text,
        technologies: _technologiesController.text.split(',').map((e) => e.trim()).toList(),
        githubLink: _githubLinkController.text,
      );

      Provider.of<ProjectController>(context, listen: false).addProject(newProject);

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('New treasure (project) has been chronicled!')), 
      );

      _formKey.currentState!.reset();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const ThemedAppBar(title: 'Captain\'s Log - Add Treasure'),
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      body: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(32.0),
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 600),
            child: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Text('Chronicle a New Discovery', style: Theme.of(context).textTheme.headlineMedium),
                  const SizedBox(height: 24),
                  TextFormField(
                    controller: _titleController,
                    decoration: const InputDecoration(labelText: 'Treasure\'s Name (Title)'),
                    validator: (value) => value!.isEmpty ? 'Every treasure needs a name!' : null,
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _descriptionController,
                    decoration: const InputDecoration(labelText: 'The Tale of This Treasure (Description)'),
                    maxLines: 5,
                    validator: (value) => value!.isEmpty ? 'A treasure\'s tale must be told!' : null,
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _imageUrlController,
                    decoration: const InputDecoration(labelText: 'Treasure Map (Image URL)'),
                    validator: (value) => value!.isEmpty ? 'Show us the treasure map!' : null,
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _technologiesController,
                    decoration: const InputDecoration(labelText: 'Ancient Runes (Technologies, comma-separated)'),
                    validator: (value) => value!.isEmpty ? 'What ancient runes were used?' : null,
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _githubLinkController,
                    decoration: const InputDecoration(labelText: 'Secret Chart (GitHub Link, optional)'),
                  ),
                  const SizedBox(height: 32),
                  ElevatedButton(
                    onPressed: _submitForm,
                    child: const Text('Add to the Hoard'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}